# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/python/projects/CalculatorLibrary/

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3.6 -m venv ~python/environments/calculator/
            . ~python/environments/calculator/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . ~python/environments/calculator/bin/activate
            flake8 --exclude=calculator* --statistics
            pytest -v --cov=calculator

  request-testing:
    type: approval
    requires:
      - build
